#ifndef PARSER_H_INCLUDED
#define PARSER_H_INCLUDED
typedef enum {
    INICIO, FIN, LEER, ESCRIBIR, ID, CONSTANTE, PARENT_IZQ, PARENT_DER, PUNTOYCOMA, COMA, ASIGNACION, SUMA, RESTA, FDT
    } TOKEN;

TOKEN scanear (FILE *archivo);

#endif // PARSER_H_INCLUDED
